.TH "bug" 3 "Martes, 7 de Agosto de 2012" "Version 0.3" "Generacion de Mapas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bug \- Lista de bugs 
 
.IP "\fBNamespace \fBcliente_lib\fP \fP" 1c
myTemperature tiene falla por el tipo de dato en formato a python '' toca pasar a '0x81', devuelve_valors fallo cuando no tiene valores 
.PP
.PP
 
.IP "\fBNamespace \fBrenderizado\fP \fP" 1c
Si la posicion del robot se sale del lienzo proboca un error en la matriz de la imagen. 
.PP
.PP
 
.IP "\fBNamespace \fBservidor_novo\fP \fP" 1c
Nada 
.PP

