.TH "cliente_lib.py" 3 "Martes, 7 de Agosto de 2012" "Version 0.3" "Generacion de Mapas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cliente_lib.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Clases"

.in +1c
.ti -1c
.RI "class \fBcliente_lib.cliente_lib\fP"
.br
.RI "\fIes la clase encargada del cliente \fP"
.in -1c
.SS "Paquetes"

.in +1c
.ti -1c
.RI "package \fBcliente_lib\fP"
.br
.PP

.RI "\fIlibreria para realizar el cliente \fP"
.in -1c
.SS "Funciones"

.in +1c
.ti -1c
.RI "def \fBcliente_lib.main\fP"
.br
.RI "\fISirve para realizar pruebas de conexion. \fP"
.in -1c
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Generacion de Mapas del código fuente.
