.TH "gamepad::gamepad" 3 "Martes, 7 de Agosto de 2012" "Version 0.3" "Generacion de Mapas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gamepad::gamepad \- 
.SH SYNOPSIS
.br
.PP
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBgamepad_init\fP"
.br
.ti -1c
.RI "def \fBgamepad_lectura\fP"
.br
.in -1c
.SS "Atributos públicos"

.in +1c
.ti -1c
.RI "\fBa\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Definición en la línea 29 del archivo gamepad.py.
.SH "Documentación del constructor y destructor"
.PP 
.SS "def gamepad.gamepad.__init__ (self)"
.PP
Definición en la línea 30 del archivo gamepad.py.
.PP
.nf
31                           :
32                 self.a=0

.fi
.SH "Documentación de las funciones miembro"
.PP 
.SS "def gamepad.gamepad.gamepad_init (self)"
.PP
Definición en la línea 33 del archivo gamepad.py.
.PP
.nf
34                               :
35                 #Abre el dispositivo js0 como si fuera un archivo de lectura
36                 pipe=open('/dev/input/js0','r')
37                 msg=[]
                return pipe,msg
.fi
.SS "def gamepad.gamepad.gamepad_lectura (self, pipe, msg)"
.PP
Definición en la línea 38 del archivo gamepad.py.
.PP
.nf
39                                           :
40                 #time.sleep(5)
41                 a=0
42                 #Para cada caracter leidos desde el /dev/input/js0 pipe..
43                 for char in pipe.read(1):
44                         #Agrega la representacion entera de la lectura de caracteres Unicode en la lista msg.
45                         msg+=[ord(char)]
46                         #print len(msg)
47                         #Si el tamanio de la lista msg es 8
48                         if len(msg) == 8:
49                                 #Boton evento si el byte 6 es 1
50                                 if msg[6] == 1: #1
51                                         if msg[4] == 0:
52                                                 if msg[7] == 0:
53                                                         #print 'Boton 1'
54                                                         a='b1'
55                                                 elif msg[7] == 1:
56                                                         #print 'Boton 2'
57                                                         a='b2'
58                                                 elif msg[7] == 2:
59                                                         #print 'Boton 3'
60                                                         a='b3'
61                                                 elif msg[7] == 3:
62                                                         #print 'Boton 4'
63                                                         a='b4'
64                                                 elif msg[7] == 4:
65                                                         #print 'Boton L1'
66                                                         a='l1'
67                                                 elif msg[7] == 5:
68                                                         #print 'Boton R1'
69                                                         a='r1'
70                                                 elif msg[7] == 6:
71                                                         #print 'Boton L2'
72                                                         a='l2'
73                                                 elif msg[7] == 7:
74                                                         #print 'Boton R2'
75                                                         a='r2'
76                                 #ejes evento if el byte 6 es 2
77                                 elif msg[6] == 2:
78                                         if msg[5] == 128:
79                                                 if msg[7] == 1:
80                                                         #print 'Boton Arriba'
81                                                         a='ar'
82                                                 elif msg[7] == 0:
83                                                         #print 'Boton Izquierda'
84                                                         a='iz'
85                                         elif msg[5] == 127:
86                                                 if msg[7] == 0:
87                                                         #print 'Boton Derecha'
88                                                         a='de'
89                                                 elif msg[7] == 1:
90                                                         #print 'Boton Abajo'
91                                                         a='ab'
92                                 #resetear msg como una lista vacia
93                                 msg[0:] = []
94                 self.a=a
                return a
.fi
.SH "Documentación de los datos miembro"
.PP 
.SS "\fBgamepad.gamepad.a\fP"
.PP
Definición en la línea 30 del archivo gamepad.py.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Generacion de Mapas del código fuente.
