.TH "renderizado.py" 3 "Martes, 7 de Agosto de 2012" "Version 0.3" "Generacion de Mapas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
renderizado.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Clases"

.in +1c
.ti -1c
.RI "class \fBrenderizado.renderizado\fP"
.br
.RI "\fIes la clase encargada de la generacion del mapa atravez de comandos. \fP"
.in -1c
.SS "Paquetes"

.in +1c
.ti -1c
.RI "package \fBrenderizado\fP"
.br
.PP

.RI "\fIprograma que utiliza la libreria openCV \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBrenderizado.a\fP = renderizado((600,400),'imagen.jpg',(13,13))"
.br
.in -1c
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Generacion de Mapas del código fuente.
