#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#       telvemap-control.py
#       
#       Copyright 2012 Danny E Vasconezz <dannyvasconeze@gmail.com>
#       
#       This program is free software; you can redistribute it and/or modify
#       it under the terms of the GNU General Public License as published by
#       the Free Software Foundation; either version 2 of the License, or
#       (at your option) any later version.
#       
#       This program is distributed in the hope that it will be useful,
#       but WITHOUT ANY WARRANTY; without even the implied warranty of
#       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#       GNU General Public License for more details.
#       
#       You should have received a copy of the GNU General Public License
#       along with this program; if not, write to the Free Software
#       Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#       MA 02110-1301, USA.
#       
#       

import AriaPy
import os
import sys
import math
import gobject
import pygtk
pygtk.require("2.0")
import gtk

#pathname = os.path.dirname(sys.argv[0])
#os.chdir(os.path.abspath(pathname))
#sys.path.append("../share/telvemap/lib")
from telvemap.gamepad import gamepad
from telvemap.FuzzyController import controlador
from telvemap.cliente_lib2 import *

def fuzzy_velocidad(setpoint,a):
	sol=-1
	try:
		a.sonares_comando()
		valor_x=a.x
		valor_y=a.y
		a.odometria_comando()
		mi_x=a.odometria[0]
		mi_y=a.odometria[1]
		dato=[]
		if (len(valor_x)>0):
			for a in range(len(valor_x)): #SIP en c. 
				#print math.sqrt(pow(valor_x['x%d' % a]-mi_x,2)+pow(valor_y['y%d' % a]-mi_y,2)), "calculo"
				dato.append(math.sqrt(pow(float(valor_x['x%d' % a])-float(mi_x),2)+pow(float(valor_y['y%d' % a])-float(mi_y),2)))
			valor_distancia=min(dato) #la distancia mas cercana tomada de la plataforma
			sol=controlador(setpoint,valor_distancia) #Controlador difuso
			if sol<0:
				sol=0
	except:
		print "Fallo calculo distancia"
		sol='e0'
	return sol

def robot_ordenes(fuzzy_vel,a,a2,b):
	aa=b
	vel=fuzzy_velocidad(fuzzy_vel,aa)
	if vel=="e0":
		print "Fallo VElocidad"
	else:
		if a2[0]=="ar":
			print "Arriba",vel
			aa.envio_movimiento("adelante",str(vel))
		elif a2[1]=="iz":
			print "Izquierda",vel
			aa.envio_movimiento("izq",str(vel))
		elif a2[1]=="de":
			print "Derecha",vel
			aa.envio_movimiento("der",str(vel))
		elif a2[0]=="ab":
			print "Abajo",vel
			aa.envio_movimiento("atras",str(vel))
		elif a=="b1":
			print "B1"
		elif a=="b2":
			print "B2"
		elif a=="b3":
			print "B3"
		elif a=="b4":
			print "B4"
		elif a=="l1":
			print "L1"
		elif a=="l2":
			print "L2"
			print "prueba"
			aa.envio_movimiento("alto") #parada de emergencia
		elif a=="r1":
			print "R1"
		elif a=="r2":
			print "R2"
		else:
			pass
		#sleep(0.2)
	return a

def etapa1(setpoint,a,aa,gamePad):
	a.palanca(gamePad)
	#print a.direccion, a.boton
	robot_ordenes(setpoint,a.boton,a.direccion,aa)
	valor=True
	if a.boton == "r1":
		valor=False
		aa.cerrar_conexion()
	return valor

def main(setpoint,ip=None,puerto=None):
	#Aria.init()
	aa=cliente_lib()
	if ip!=None:
		aa.ip=ip
		aa.puerto=puerto
	aa.conexion()
	a=gamepad()
	gamePad=a.iniciar()
	a.hombre_muerto="r2" #Si no se preciona no lee informacion del gamepad
	a.palanca(gamePad)
	# Inicio de la parte grafica mapas
	
	# Timer que se repite cada 100ms con sus parametros
	#gobject.threads_init()
	source_id=gobject.timeout_add(100,etapa1,setpoint,a,aa,gamePad)
	#loop = gobject.MainLoop()
	#loop.run()
	# Fin del Timer
	
	
	#Inicio de gtk
	direccion="/usr/local/share/telvemap/" ##Correguir para la instalcion en otro dirrecion
	builder = gtk.Builder() #El archivo de glade debe estar en gtkbuilder
	builder.add_from_file("GUI2.glade")#direccion+"glade/GUI.glade") #Carga el archivo glade
	builder.connect_signals(builder) #Toma todas las senales de glade
	teleoper = builder.get_object("map") #Ventana principal
	#boton = builder.get_object("button1")
	#area=builder.get_object("mapa")
	teleoper.show()
	
	gtk.main()

if __name__ == '__main__':
	setpoint=150
	#ip="192.168.2.113"
	#puerto=9991
	main(setpoint)#,ip,puerto)

