.TH "gamepad.py" 3 "Martes, 7 de Agosto de 2012" "Version 0.1" "Generacion de Mapas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gamepad.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Clases"

.in +1c
.ti -1c
.RI "class \fBgamepad.gamepad\fP"
.br
.in -1c
.SS "Paquetes"

.in +1c
.ti -1c
.RI "package \fBgamepad\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBgamepad.c\fP = gamepad()"
.br
.ti -1c
.RI "tuple \fBgamepad.a\fP = c.gamepad_lectura(pipe,msg)"
.br
.in -1c
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Generacion de Mapas del código fuente.
