.TH "inicio.py" 3 "Martes, 7 de Agosto de 2012" "Version 0.1" "Generacion de Mapas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inicio.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Clases"

.in +1c
.ti -1c
.RI "class \fBinicio.prueba_adqui\fP"
.br
.RI "\fIes la clase encargada del entorno grafico y enlace con \fBcliente_lib\fP \fP"
.in -1c
.SS "Paquetes"

.in +1c
.ti -1c
.RI "package \fBinicio\fP"
.br
.in -1c
.SS "Funciones"

.in +1c
.ti -1c
.RI "def \fBinicio.main\fP"
.br
.RI "\fIEl encargado al momento de ejcutar la aplicacion de instanciar el objeto prueba_teleoperacion. \fP"
.in -1c
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Generacion de Mapas del código fuente.
